# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "xilinx-provision"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Victor Costan"]
  s.date = "2012-01-13"
  s.description = "Wraps the impact CLI tool in the Xilinx ISE"
  s.email = "victor@costan.us"
  s.executables = ["xilinx-provision", "xilinx-provision-setup"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".project",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/xilinx-provision",
    "bin/xilinx-provision-setup",
    "lib/xilinx/provision.rb",
    "lib/xilinx/provision/cable_driver.rb",
    "lib/xilinx/provision/cable_firmware.rb",
    "lib/xilinx/provision/impact.rb",
    "lib/xilinx/provision/udev.rb",
    "spec/fixtures/ethernet_ping.bit",
    "spec/fixtures/impact_detect",
    "spec/fixtures/snippet.rules",
    "spec/spec_helper.rb",
    "spec/xilinx/provision/cable_driver_spec.rb",
    "spec/xilinx/provision/cable_firmware_spec.rb",
    "spec/xilinx/provision/impact_spec.rb",
    "spec/xilinx/provision/udev_spec.rb",
    "spec/xilinx/provision_spec.rb",
    "xilinx-provision.gemspec"
  ]
  s.homepage = "http://github.com/csail/xilinx-provision"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Deploys bitfiles to Xilinx FPGAs"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rdoc>, [">= 3.12"])
      s.add_development_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.14"])
      s.add_development_dependency(%q<jeweler>, [">= 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<ether_ping>, [">= 0.3.1"])
    else
      s.add_dependency(%q<rdoc>, [">= 3.12"])
      s.add_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_dependency(%q<bundler>, [">= 1.0.14"])
      s.add_dependency(%q<jeweler>, [">= 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<ether_ping>, [">= 0.3.1"])
    end
  else
    s.add_dependency(%q<rdoc>, [">= 3.12"])
    s.add_dependency(%q<rspec>, [">= 2.8.0"])
    s.add_dependency(%q<bundler>, [">= 1.0.14"])
    s.add_dependency(%q<jeweler>, [">= 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<ether_ping>, [">= 0.3.1"])
  end
end

